package frames;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import javax.swing.SwingConstants;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import javax.swing.border.MatteBorder;
import javax.swing.JLabel;
import javax.swing.border.EmptyBorder;

import file_tools.FontFile;

public class JFontChooser extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    //the font
    private Font font;
    
    //Constructors
    /** Creates new form JFontChooser */
    public JFontChooser(java.awt.Frame parent, Font font) {
        super(parent);
        this.font = font;
        initComponents();
        lblPreview.setFont(font);
    }
    
    public JFontChooser(java.awt.Frame parent) {
        super(parent);
        this.font = new Font("Dialog",Font.PLAIN,12);
        initComponents();
        lblPreview.setFont(font);
    }
    
    public JFontChooser(Font font) {
        super((javax.swing.JFrame)null);
        this.font = font;
        initComponents();
        lblPreview.setFont(font);
    }
    
    public JFontChooser() {
        super((javax.swing.JFrame)null);
        this.font = new Font("Dialog",Font.PLAIN,12);
        initComponents();
        lblPreview.setFont(font);
    }
    
    /** @return the font chosen by the user */
    public Font getFont(){
        return font;
    }
    
    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        fontPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFont = new javax.swing.JList(GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames());
       // lstFont = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstStyle = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstSize = new javax.swing.JList();
        previewPanel = new javax.swing.JPanel();
        lblPreview = new javax.swing.JLabel();
        lblPreview.setHorizontalAlignment(SwingConstants.CENTER);
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        SetDefaultButton = new javax.swing.JButton();

        setTitle("\u062A\u062D\u062F\u064A\u062F \u0627\u0644\u062E\u0637");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        fontPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("\u0639\u0627\u0626\u0644\u0629 \u0627\u0644\u062E\u0637\u0648\u0637");
        jLabel1.applyComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jLabel1.setFont(new Font("Arial", Font.BOLD, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        gridBagConstraints.weightx = 2.0;
        fontPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("\u0646\u0645\u0637 \u0627\u0644\u062E\u0637");
        jLabel2.applyComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jLabel2.setFont(new Font("Arial", Font.BOLD, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        fontPanel.add(jLabel2, gridBagConstraints);

        jLabel3.setText("\u062D\u062C\u0645 \u0627\u0644\u062E\u0637");
        jLabel3.applyComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jLabel3.setFont(new Font("Arial", Font.BOLD, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        gridBagConstraints.weightx = 0.2;
        fontPanel.add(jLabel3, gridBagConstraints);
        
        lstFont.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Adobe Arabic", "Adobe Naskh Medium", "Andalus",
            					 "Arabic Typesetting", "Arial", "Arial Unicode MS",
            					 "Courier New", "Dialog", "DialogInput",
            					 "Lucida Bright", "Lucida Sans", "Lucida Sans Typewriter",
            					 "Microsoft Sans Serif", "Microsoft Uighur", "Monospaced",
            					 "Myriad Arabic","Sakkal Majalla","SansSerif","Segoe UI",
            					 "Serif","Simplified Arabic","Simplified Arabic Fixed",
            					 "Tahoma", "Times New Roman","Traditional Arabic"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });

        lstFont.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstFont.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstFontValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(lstFont);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        gridBagConstraints.weightx = 2.0;
        fontPanel.add(jScrollPane1, gridBagConstraints);

        lstStyle.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Plain", "Bold", "Italic", "Bold Italic" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstStyle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstStyle.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstStyleValueChanged(evt);
            }
        });

        jScrollPane2.setViewportView(lstStyle);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        fontPanel.add(jScrollPane2, gridBagConstraints);

        lstSize.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "8", "10", "11", "12", "14", "16", "20", "24" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstSize.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstSize.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstSizeValueChanged(evt);
            }
        });
        mainPanel.setLayout(new BorderLayout());

        jScrollPane3.setViewportView(lstSize);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        gridBagConstraints.weightx = 0.2;
        fontPanel.add(jScrollPane3, gridBagConstraints);

        mainPanel.add(fontPanel, BorderLayout.CENTER);
        previewPanel.setBorder(new javax.swing.border.TitledBorder(null, "معاينة", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", Font.BOLD, 14)));
        previewPanel.applyComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        lblPreview.applyComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        
        panel = new JPanel();
        panel.setBorder(new MatteBorder(0, 0, 1, 0, (Color) Color.GRAY));
        panel.setBackground(Color.WHITE);
        getContentPane().add(panel, BorderLayout.NORTH);
        panel.setLayout(new GridLayout(2, 1, 0, 0));
        
        label = new JLabel("تحديد الخط");
        label.setFont(new Font("Arial", Font.BOLD, 20));
        label.setBorder(new EmptyBorder(10, 0, 0, 30));
        label.applyComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        panel.add(label);
        
        label_1 = new JLabel("يمكنك تحديد الخط المناسب لكتابة البرنامج");
        label_1.applyComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        label_1.setVerticalAlignment(SwingConstants.TOP);
        label_1.setFont(new Font("Arial", Font.BOLD, 14));
        label_1.setBorder(new EmptyBorder(10, 0, 0, 50));
        panel.add(label_1);
        previewPanel.setLayout(new GridLayout(0, 1, 0, 0));
        lblPreview.setFont(new java.awt.Font("Dialog", 0, 12));
        lblPreview.setText("\u0623\u0628\u062C\u062F \u0647\u0648\u0632");
        previewPanel.add(lblPreview);
        
        previewPanel.setPreferredSize(new Dimension(getWidth(),100));

        mainPanel.add(previewPanel,BorderLayout.SOUTH);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setText("موافق");
        okButton.setHorizontalAlignment(SwingConstants.RIGHT);
        okButton.setFont(new Font("Arial", Font.BOLD, 14));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(okButton);
        
        SetDefaultButton.setText("تعيين الافتراضي");
        SetDefaultButton.setHorizontalAlignment(SwingConstants.RIGHT);
        SetDefaultButton.setFont(new Font("Arial", Font.BOLD, 14));
        SetDefaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	SetDefaultButtonActionPerformed(evt);
            }

			private void SetDefaultButtonActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				Font defaultFont = new Font("Garamond", Font.BOLD, 14);
				for (int i=0; i<PrincipalWindow.tabbedPaneProgram.getTabCount(); i++){
			    	JPanel panelToSetFont = (JPanel) PrincipalWindow.tabbedPaneProgram.getComponentAt(i);
					JScrollPane scrollpane = (JScrollPane) panelToSetFont.getComponent(0);
					JTextPane textPane = (JTextPane) scrollpane.getViewport().getComponent(0);
					textPane.setFont(defaultFont);
					textPane.repaint();
			    	}
			    	PrincipalWindow.tabbedPaneProgram.setSelectedIndex(PrincipalWindow.tabbedPaneProgram.getTabCount()-1);
			    	FontFile.saveFont(defaultFont);
			        doClose(RET_OK);
				
			}
        });

        buttonPanel.add(SetDefaultButton);

        cancelButton.setText("إلغاء الأمر");
        cancelButton.setFont(new Font("Arial", Font.BOLD, 14));
        cancelButton.setHorizontalAlignment(SwingConstants.RIGHT);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(443, 429));
        setLocation((screenSize.width-443)/2,(screenSize.height-429)/2);
    }//GEN-END:initComponents

    private void lstStyleValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstStyleValueChanged
        int style = -1;
        String selStyle = (String)lstStyle.getSelectedValue();
        if(selStyle=="Plain")
            style = Font.PLAIN;
        if(selStyle=="Bold")
            style = Font.BOLD;
        if(selStyle=="Italic")
            style = Font.ITALIC;
        if(selStyle=="Bold Italic")
            style = Font.BOLD + Font.ITALIC;
        
        font = new Font(font.getFamily(),style,font.getSize());
        lblPreview.setFont(font);
    }//GEN-LAST:event_lstStyleValueChanged

    private void lstSizeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstSizeValueChanged
        int size = Integer.parseInt((String)lstSize.getSelectedValue());
        font = new Font(font.getFamily(),font.getStyle(),size);
        lblPreview.setFont(font);
    }//GEN-LAST:event_lstSizeValueChanged

    private void lstFontValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstFontValueChanged
        font = new Font((String)lstFont.getSelectedValue(),font.getStyle(),font.getSize());
        lblPreview.setFont(font);
    }//GEN-LAST:event_lstFontValueChanged
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    	
    	for (int i=0; i<PrincipalWindow.tabbedPaneProgram.getTabCount(); i++){
    	JPanel panelToSetFont = (JPanel) PrincipalWindow.tabbedPaneProgram.getComponentAt(i);
		JScrollPane scrollpane = (JScrollPane) panelToSetFont.getComponent(0);
		JTextPane textPane = (JTextPane) scrollpane.getViewport().getComponent(0);
		textPane.setFont(lblPreview.getFont());
		textPane.repaint();
    	}
    	PrincipalWindow.tabbedPaneProgram.setSelectedIndex(PrincipalWindow.tabbedPaneProgram.getTabCount()-1);
    	FontFile.saveFont(lblPreview.getFont());
    	
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fontPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList lstSize;
    private javax.swing.JButton okButton;
    private javax.swing.JButton SetDefaultButton;
    private javax.swing.JList lstFont;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstStyle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel previewPanel;
    private javax.swing.JLabel lblPreview;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
    
    private int returnStatus = RET_CANCEL;
    private JPanel panel;
    private JLabel label;
    private JLabel label_1;
}